apiVersion: apps/v1
kind: Deployment
metadata:
    name: publisher
    namespace: c6o-system
    labels:
        role: system
        app: publisher
        version: v1
spec:
    selector:
        matchLabels:
          role: system
          app: publisher
          version: v1
    replicas: 1
    template:
        metadata:
            labels:
              role: system
              app: publisher
              version: v1
        spec:
            containers:
            - env:
              - name: PORT
                value: "10002"
              - name: QUEUE_ADDRESS
                value: "amqp://rabbitmq:5672/"
              - name: ETCD_CONNECTION
                value: "etcd-client:2379"
              - name: LOGLEVEL
                value: "0"
              name: publisher
              image: c6oio/system-publisher:canary
              imagePullPolicy: Always
              ports:
                - containerPort: 10002
---
apiVersion: v1
kind: Service
metadata:
  namespace: c6o-system
  name: publisher
  labels:
    role: system
    app: publisher
spec:
  selector:
    role: system
    app: publisher
  ports:
    - port: 10002
      protocol: TCP
      targetPort: 10002
      name: http2
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: subscriber
    namespace: c6o-system
    labels:
        role: system
        app: subscriber
        version: v1
spec:
    selector:
        matchLabels:
          role: system
          app: subscriber
          version: v1
    replicas: 1
    template:
        metadata:
            labels:
              role: system
              app: subscriber
              version: v1
        spec:
            containers:
            - env:
              - name: PORT
                value: "10001"
              - name: QUEUE_ADDRESS
                value: "amqp://rabbitmq:5672/"
              - name: ETCD_CONNECTION
                value: "etcd-client:2379"
              - name: LOGLEVEL
                value: "0"
              name: subscriber
              image: c6oio/system-subscriber:canary
              imagePullPolicy: Always
              ports:
                - containerPort: 10001
---
apiVersion: v1
kind: Service
metadata:
  namespace: c6o-system
  name: subscriber
  labels:
    role: system
    app: subscriber
spec:
  selector:
    role: system
    app: subscriber
  ports:
    - port: 10001
      protocol: TCP
      targetPort: 10001
      name: http2